const PDFDocument = require("pdfkit");

const generateInvoice = (payment, res) => {
    const doc = new PDFDocument({
        margin: 50
    });

    res.setHeader("Content-Type", "application/pdf");
    res.setHeader(
        "Content-Disposition",
        `attachment; filename=invoice-${payment._id}.pdf`
    );

    doc.pipe(res);

    // HEADER
    doc
        .fontSize(24)
        .text("UNFAZED", { align: "center" });

    doc
        .fontSize(16)
        .text("Therapy Session Invoice", { align: "center" });

    doc.moveDown(2);

    // INVOICE DETAILS
    doc
        .fontSize(11)
        .text(`Invoice ID: ${payment._id}`)
        .text(`Date: ${new Date().toLocaleDateString()}`);

    doc.moveDown();

    // CLIENT
    doc
        .fontSize(14)
        .text("Client Details");

    doc
        .fontSize(11)
        .text(`Name: ${payment.clientName}`)
        .text(`Email: ${payment.clientEmail}`);

    doc.moveDown();

    // PAYMENT
    doc
        .fontSize(14)
        .text("Payment Details");

    doc
        .fontSize(11)
        .text(`Payment ID: ${payment.gatewayTransactionId}`)
        .text(`Status: ${payment.status}`)
        .text(`Amount: ₹${payment.amount.toFixed(2)}`)
        .text(`Platform Fee: ₹${payment.platformFee.toFixed(2)}`)
        .text(`Net Amount: ₹${payment.netAmount.toFixed(2)}`);

    doc.moveDown();

    // GST STYLE SUMMARY
    const gst = payment.amount * 0.18;

    doc
        .fontSize(14)
        .text("GST-Style Tax Summary");

    doc
        .fontSize(11)
        .text(`Taxable Amount: ₹${payment.amount.toFixed(2)}`)
        .text(`GST (18%): ₹${gst.toFixed(2)}`)
        .text(
            `Total Amount: ₹${(payment.amount + gst).toFixed(2)}`
        );

    doc.moveDown(2);

    doc
        .fontSize(10)
        .text(
            "This is a test-mode invoice generated by the Unfazed platform."
        );

    doc
        .moveDown()
        .text(
            "Thank you for using Unfazed."
        );

    doc.end();
};

module.exports = {
    generateInvoice
};